/* tslint:disable */

/* eslint-disable */

/**
 * BlockInfrastructure-Core
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { AxiosInstance, AxiosPromise, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';

// @ts-ignore
import {
  BASE_PATH,
  BaseAPI,
  COLLECTION_FORMATS,
  RequestArgs,
  RequiredError,
} from '../base';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  createRequestFunction,
  serializeDataIfNeeded,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  toPathString,
} from '../common';
import type { Configuration } from '../configuration';
// @ts-ignore
import { ErrorResponse } from '../model';
// @ts-ignore
import { InstallPluginRequest } from '../model';
// @ts-ignore
import { PluginProjection } from '../model';

/**
 * PluginApi - axios parameter creator
 * @export
 */
export const PluginApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     *
     * @summary 채널에 플러그인을 설치합니다.
     * @param {string} channelId 플러그인을 설치할 채널 Id
     * @param {InstallPluginRequest} [InstallPluginRequest] 플러그인 설치 요청
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    installPluginToChannelAsync: async (
      channelId: string,
      InstallPluginRequest?: InstallPluginRequest,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'channelId' is not null or undefined
      assertParamExists('installPluginToChannelAsync', 'channelId', channelId);
      const localVarPath = `/channels/{channelId}/plugins/install`.replace(
        `{${'channelId'}}`,
        encodeURIComponent(String(channelId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'POST',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication JwtAuthenticationFilter required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        InstallPluginRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary 서비스에서 허용하는 플러그인을 모두 리스팅 합니다.
     * @param {string} channelId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listAvailablePlugins: async (
      channelId: string,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'channelId' is not null or undefined
      assertParamExists('listAvailablePlugins', 'channelId', channelId);
      const localVarPath = `/channels/{channelId}/plugins/available`.replace(
        `{${'channelId'}}`,
        encodeURIComponent(String(channelId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'GET',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication JwtAuthenticationFilter required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * PluginApi - functional programming interface
 * @export
 */
export const PluginApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = PluginApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @summary 채널에 플러그인을 설치합니다.
     * @param {string} channelId 플러그인을 설치할 채널 Id
     * @param {InstallPluginRequest} [InstallPluginRequest] 플러그인 설치 요청
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async installPluginToChannelAsync(
      channelId: string,
      InstallPluginRequest?: InstallPluginRequest,
      options?: AxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.installPluginToChannelAsync(
          channelId,
          InstallPluginRequest,
          options,
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
    /**
     *
     * @summary 서비스에서 허용하는 플러그인을 모두 리스팅 합니다.
     * @param {string} channelId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async listAvailablePlugins(
      channelId: string,
      options?: AxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<Array<PluginProjection>>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.listAvailablePlugins(
          channelId,
          options,
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
  };
};

/**
 * PluginApi - factory interface
 * @export
 */
export const PluginApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = PluginApiFp(configuration);
  return {
    /**
     *
     * @summary 채널에 플러그인을 설치합니다.
     * @param {string} channelId 플러그인을 설치할 채널 Id
     * @param {InstallPluginRequest} [InstallPluginRequest] 플러그인 설치 요청
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    installPluginToChannelAsync(
      channelId: string,
      InstallPluginRequest?: InstallPluginRequest,
      options?: any,
    ): AxiosPromise<void> {
      return localVarFp
        .installPluginToChannelAsync(channelId, InstallPluginRequest, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary 서비스에서 허용하는 플러그인을 모두 리스팅 합니다.
     * @param {string} channelId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listAvailablePlugins(
      channelId: string,
      options?: any,
    ): AxiosPromise<Array<PluginProjection>> {
      return localVarFp
        .listAvailablePlugins(channelId, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * PluginApi - object-oriented interface
 * @export
 * @class PluginApi
 * @extends {BaseAPI}
 */
export class PluginApi extends BaseAPI {
  /**
   *
   * @summary 채널에 플러그인을 설치합니다.
   * @param {string} channelId 플러그인을 설치할 채널 Id
   * @param {InstallPluginRequest} [InstallPluginRequest] 플러그인 설치 요청
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PluginApi
   */
  public installPluginToChannelAsync(
    channelId: string,
    InstallPluginRequest?: InstallPluginRequest,
    options?: AxiosRequestConfig,
  ) {
    return PluginApiFp(this.configuration)
      .installPluginToChannelAsync(channelId, InstallPluginRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary 서비스에서 허용하는 플러그인을 모두 리스팅 합니다.
   * @param {string} channelId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PluginApi
   */
  public listAvailablePlugins(channelId: string, options?: AxiosRequestConfig) {
    return PluginApiFp(this.configuration)
      .listAvailablePlugins(channelId, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
