/* tslint:disable */

/* eslint-disable */

/**
 * BlockInfrastructure-Core
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { AxiosInstance, AxiosPromise, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';

// @ts-ignore
import {
  BASE_PATH,
  BaseAPI,
  COLLECTION_FORMATS,
  RequestArgs,
  RequiredError,
} from '../base';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  createRequestFunction,
  serializeDataIfNeeded,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  toPathString,
} from '../common';
import type { Configuration } from '../configuration';
// @ts-ignore
import { ErrorResponse } from '../model';
// @ts-ignore
import { PricingInformationProjection } from '../model';

/**
 * PricingApi - axios parameter creator
 * @export
 */
export const PricingApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     *
     * @summary 서버에 등록된 모든 가격 정보를 불러옵니다.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAllPricingInformationAsync: async (
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/pricing`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'GET',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication JwtAuthenticationFilter required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * PricingApi - functional programming interface
 * @export
 */
export const PricingApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = PricingApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @summary 서버에 등록된 모든 가격 정보를 불러옵니다.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getAllPricingInformationAsync(
      options?: AxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<Array<PricingInformationProjection>>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.getAllPricingInformationAsync(options);
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
  };
};

/**
 * PricingApi - factory interface
 * @export
 */
export const PricingApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = PricingApiFp(configuration);
  return {
    /**
     *
     * @summary 서버에 등록된 모든 가격 정보를 불러옵니다.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAllPricingInformationAsync(
      options?: any,
    ): AxiosPromise<Array<PricingInformationProjection>> {
      return localVarFp
        .getAllPricingInformationAsync(options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * PricingApi - object-oriented interface
 * @export
 * @class PricingApi
 * @extends {BaseAPI}
 */
export class PricingApi extends BaseAPI {
  /**
   *
   * @summary 서버에 등록된 모든 가격 정보를 불러옵니다.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PricingApi
   */
  public getAllPricingInformationAsync(options?: AxiosRequestConfig) {
    return PricingApiFp(this.configuration)
      .getAllPricingInformationAsync(options)
      .then((request) => request(this.axios, this.basePath));
  }
}
