/* tslint:disable */

/* eslint-disable */

/**
 * BlockInfrastructure-Core
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { AxiosInstance, AxiosPromise, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';

// @ts-ignore
import {
  BASE_PATH,
  BaseAPI,
  COLLECTION_FORMATS,
  RequestArgs,
  RequiredError,
} from '../base';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  createRequestFunction,
  serializeDataIfNeeded,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  toPathString,
} from '../common';
import type { Configuration } from '../configuration';
// @ts-ignore
import { ErrorResponse } from '../model';
// @ts-ignore
import { SketchResponse } from '../model';

/**
 * SketchApi - axios parameter creator
 * @export
 */
export const SketchApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     * 이 API는 채널의 Owner, Reader 모두 조회할 수 있습니다.
     * @summary 채널 내에 있는 모든 스케치를 가져옵니다,
     * @param {string} channelId 조회할 채널 ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listSketchesInChannelAsync: async (
      channelId: string,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'channelId' is not null or undefined
      assertParamExists('listSketchesInChannelAsync', 'channelId', channelId);
      const localVarPath = `/channels/{channelId}/sketches`.replace(
        `{${'channelId'}}`,
        encodeURIComponent(String(channelId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'GET',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication JwtAuthenticationFilter required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * SketchApi - functional programming interface
 * @export
 */
export const SketchApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = SketchApiAxiosParamCreator(configuration);
  return {
    /**
     * 이 API는 채널의 Owner, Reader 모두 조회할 수 있습니다.
     * @summary 채널 내에 있는 모든 스케치를 가져옵니다,
     * @param {string} channelId 조회할 채널 ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async listSketchesInChannelAsync(
      channelId: string,
      options?: AxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<Array<SketchResponse>>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.listSketchesInChannelAsync(
          channelId,
          options,
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
  };
};

/**
 * SketchApi - factory interface
 * @export
 */
export const SketchApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = SketchApiFp(configuration);
  return {
    /**
     * 이 API는 채널의 Owner, Reader 모두 조회할 수 있습니다.
     * @summary 채널 내에 있는 모든 스케치를 가져옵니다,
     * @param {string} channelId 조회할 채널 ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listSketchesInChannelAsync(
      channelId: string,
      options?: any,
    ): AxiosPromise<Array<SketchResponse>> {
      return localVarFp
        .listSketchesInChannelAsync(channelId, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * SketchApi - object-oriented interface
 * @export
 * @class SketchApi
 * @extends {BaseAPI}
 */
export class SketchApi extends BaseAPI {
  /**
   * 이 API는 채널의 Owner, Reader 모두 조회할 수 있습니다.
   * @summary 채널 내에 있는 모든 스케치를 가져옵니다,
   * @param {string} channelId 조회할 채널 ID
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SketchApi
   */
  public listSketchesInChannelAsync(
    channelId: string,
    options?: AxiosRequestConfig,
  ) {
    return SketchApiFp(this.configuration)
      .listSketchesInChannelAsync(channelId, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
