/* tslint:disable */
/* eslint-disable */
/**
 * BlockInfrastructure-Core
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { CreateSketchRequest } from '../model';
// @ts-ignore
import { DeploymentProjection } from '../model';
// @ts-ignore
import { ErrorResponse } from '../model';
// @ts-ignore
import { SketchResponse } from '../model';
// @ts-ignore
import { UpdateSketchRequest } from '../model';
/**
 * SketchApi - axios parameter creator
 * @export
 */
export const SketchApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 이 API는 채널의 Owner만 사용할 수 있습니다.
         * @summary 채널 내에 빈 스케치를 새로 추가합니다.
         * @param {string} channelId 채널 ID
         * @param {CreateSketchRequest} [CreateSketchRequest] 스케치 생성 요청
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSketchAsync: async (channelId: string, CreateSketchRequest?: CreateSketchRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'channelId' is not null or undefined
            assertParamExists('createSketchAsync', 'channelId', channelId)
            const localVarPath = `/channels/{channelId}/sketches`
                .replace(`{${"channelId"}}`, encodeURIComponent(String(channelId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JwtAuthenticationFilter required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(CreateSketchRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 해당 API는 Blocking API가 아닌, Non-Blocking API이며, 응답으로는 배포의 상황을 조회할 수 있는 DeploymentProjection을 반환합니다.
         * @summary 배포를 시작합니다.
         * @param {string} sketchId 
         * @param {string} channelId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deploySketchAsync: async (sketchId: string, channelId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sketchId' is not null or undefined
            assertParamExists('deploySketchAsync', 'sketchId', sketchId)
            // verify required parameter 'channelId' is not null or undefined
            assertParamExists('deploySketchAsync', 'channelId', channelId)
            const localVarPath = `/channels/{channelId}/sketches/{sketchId}/deploy`
                .replace(`{${"sketchId"}}`, encodeURIComponent(String(sketchId)))
                .replace(`{${"channelId"}}`, encodeURIComponent(String(channelId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JwtAuthenticationFilter required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 특정 스케치를 불러옵니다.
         * @param {string} channelId 채널 ID
         * @param {string} sketchId 가져올 특정 스케치 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSketchAsync: async (channelId: string, sketchId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'channelId' is not null or undefined
            assertParamExists('getSketchAsync', 'channelId', channelId)
            // verify required parameter 'sketchId' is not null or undefined
            assertParamExists('getSketchAsync', 'sketchId', sketchId)
            const localVarPath = `/channels/{channelId}/sketches/{sketchId}`
                .replace(`{${"channelId"}}`, encodeURIComponent(String(channelId)))
                .replace(`{${"sketchId"}}`, encodeURIComponent(String(sketchId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JwtAuthenticationFilter required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 이 API는 채널의 Owner, Reader 모두 조회할 수 있습니다.
         * @summary 채널 내에 있는 모든 스케치를 가져옵니다,
         * @param {string} channelId 조회할 채널 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSketchesInChannelAsync: async (channelId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'channelId' is not null or undefined
            assertParamExists('listSketchesInChannelAsync', 'channelId', channelId)
            const localVarPath = `/channels/{channelId}/sketches`
                .replace(`{${"channelId"}}`, encodeURIComponent(String(channelId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JwtAuthenticationFilter required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 스케치를 업데이트 합니다.
         * @param {string} channelId 채널 ID
         * @param {string} sketchId 업데이트 할 스케치 ID
         * @param {UpdateSketchRequest} [UpdateSketchRequest] 업데이트 할 스케치 내용
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSketchAsync: async (channelId: string, sketchId: string, UpdateSketchRequest?: UpdateSketchRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'channelId' is not null or undefined
            assertParamExists('updateSketchAsync', 'channelId', channelId)
            // verify required parameter 'sketchId' is not null or undefined
            assertParamExists('updateSketchAsync', 'sketchId', sketchId)
            const localVarPath = `/channels/{channelId}/sketches/{sketchId}`
                .replace(`{${"channelId"}}`, encodeURIComponent(String(channelId)))
                .replace(`{${"sketchId"}}`, encodeURIComponent(String(sketchId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JwtAuthenticationFilter required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(UpdateSketchRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SketchApi - functional programming interface
 * @export
 */
export const SketchApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SketchApiAxiosParamCreator(configuration)
    return {
        /**
         * 이 API는 채널의 Owner만 사용할 수 있습니다.
         * @summary 채널 내에 빈 스케치를 새로 추가합니다.
         * @param {string} channelId 채널 ID
         * @param {CreateSketchRequest} [CreateSketchRequest] 스케치 생성 요청
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createSketchAsync(channelId: string, CreateSketchRequest?: CreateSketchRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SketchResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createSketchAsync(channelId, CreateSketchRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 해당 API는 Blocking API가 아닌, Non-Blocking API이며, 응답으로는 배포의 상황을 조회할 수 있는 DeploymentProjection을 반환합니다.
         * @summary 배포를 시작합니다.
         * @param {string} sketchId 
         * @param {string} channelId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deploySketchAsync(sketchId: string, channelId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeploymentProjection>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deploySketchAsync(sketchId, channelId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 특정 스케치를 불러옵니다.
         * @param {string} channelId 채널 ID
         * @param {string} sketchId 가져올 특정 스케치 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSketchAsync(channelId: string, sketchId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SketchResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSketchAsync(channelId, sketchId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 이 API는 채널의 Owner, Reader 모두 조회할 수 있습니다.
         * @summary 채널 내에 있는 모든 스케치를 가져옵니다,
         * @param {string} channelId 조회할 채널 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listSketchesInChannelAsync(channelId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<SketchResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listSketchesInChannelAsync(channelId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 스케치를 업데이트 합니다.
         * @param {string} channelId 채널 ID
         * @param {string} sketchId 업데이트 할 스케치 ID
         * @param {UpdateSketchRequest} [UpdateSketchRequest] 업데이트 할 스케치 내용
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateSketchAsync(channelId: string, sketchId: string, UpdateSketchRequest?: UpdateSketchRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SketchResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateSketchAsync(channelId, sketchId, UpdateSketchRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * SketchApi - factory interface
 * @export
 */
export const SketchApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SketchApiFp(configuration)
    return {
        /**
         * 이 API는 채널의 Owner만 사용할 수 있습니다.
         * @summary 채널 내에 빈 스케치를 새로 추가합니다.
         * @param {string} channelId 채널 ID
         * @param {CreateSketchRequest} [CreateSketchRequest] 스케치 생성 요청
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSketchAsync(channelId: string, CreateSketchRequest?: CreateSketchRequest, options?: any): AxiosPromise<SketchResponse> {
            return localVarFp.createSketchAsync(channelId, CreateSketchRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 해당 API는 Blocking API가 아닌, Non-Blocking API이며, 응답으로는 배포의 상황을 조회할 수 있는 DeploymentProjection을 반환합니다.
         * @summary 배포를 시작합니다.
         * @param {string} sketchId 
         * @param {string} channelId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deploySketchAsync(sketchId: string, channelId: string, options?: any): AxiosPromise<DeploymentProjection> {
            return localVarFp.deploySketchAsync(sketchId, channelId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 특정 스케치를 불러옵니다.
         * @param {string} channelId 채널 ID
         * @param {string} sketchId 가져올 특정 스케치 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSketchAsync(channelId: string, sketchId: string, options?: any): AxiosPromise<SketchResponse> {
            return localVarFp.getSketchAsync(channelId, sketchId, options).then((request) => request(axios, basePath));
        },
        /**
         * 이 API는 채널의 Owner, Reader 모두 조회할 수 있습니다.
         * @summary 채널 내에 있는 모든 스케치를 가져옵니다,
         * @param {string} channelId 조회할 채널 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSketchesInChannelAsync(channelId: string, options?: any): AxiosPromise<Array<SketchResponse>> {
            return localVarFp.listSketchesInChannelAsync(channelId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 스케치를 업데이트 합니다.
         * @param {string} channelId 채널 ID
         * @param {string} sketchId 업데이트 할 스케치 ID
         * @param {UpdateSketchRequest} [UpdateSketchRequest] 업데이트 할 스케치 내용
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSketchAsync(channelId: string, sketchId: string, UpdateSketchRequest?: UpdateSketchRequest, options?: any): AxiosPromise<SketchResponse> {
            return localVarFp.updateSketchAsync(channelId, sketchId, UpdateSketchRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SketchApi - object-oriented interface
 * @export
 * @class SketchApi
 * @extends {BaseAPI}
 */
export class SketchApi extends BaseAPI {
    /**
     * 이 API는 채널의 Owner만 사용할 수 있습니다.
     * @summary 채널 내에 빈 스케치를 새로 추가합니다.
     * @param {string} channelId 채널 ID
     * @param {CreateSketchRequest} [CreateSketchRequest] 스케치 생성 요청
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SketchApi
     */
    public createSketchAsync(channelId: string, CreateSketchRequest?: CreateSketchRequest, options?: AxiosRequestConfig) {
        return SketchApiFp(this.configuration).createSketchAsync(channelId, CreateSketchRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 해당 API는 Blocking API가 아닌, Non-Blocking API이며, 응답으로는 배포의 상황을 조회할 수 있는 DeploymentProjection을 반환합니다.
     * @summary 배포를 시작합니다.
     * @param {string} sketchId 
     * @param {string} channelId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SketchApi
     */
    public deploySketchAsync(sketchId: string, channelId: string, options?: AxiosRequestConfig) {
        return SketchApiFp(this.configuration).deploySketchAsync(sketchId, channelId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 특정 스케치를 불러옵니다.
     * @param {string} channelId 채널 ID
     * @param {string} sketchId 가져올 특정 스케치 ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SketchApi
     */
    public getSketchAsync(channelId: string, sketchId: string, options?: AxiosRequestConfig) {
        return SketchApiFp(this.configuration).getSketchAsync(channelId, sketchId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 이 API는 채널의 Owner, Reader 모두 조회할 수 있습니다.
     * @summary 채널 내에 있는 모든 스케치를 가져옵니다,
     * @param {string} channelId 조회할 채널 ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SketchApi
     */
    public listSketchesInChannelAsync(channelId: string, options?: AxiosRequestConfig) {
        return SketchApiFp(this.configuration).listSketchesInChannelAsync(channelId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 스케치를 업데이트 합니다.
     * @param {string} channelId 채널 ID
     * @param {string} sketchId 업데이트 할 스케치 ID
     * @param {UpdateSketchRequest} [UpdateSketchRequest] 업데이트 할 스케치 내용
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SketchApi
     */
    public updateSketchAsync(channelId: string, sketchId: string, UpdateSketchRequest?: UpdateSketchRequest, options?: AxiosRequestConfig) {
        return SketchApiFp(this.configuration).updateSketchAsync(channelId, sketchId, UpdateSketchRequest, options).then((request) => request(this.axios, this.basePath));
    }
}
