/* tslint:disable */
/* eslint-disable */
/**
 * BlockInfrastructure-Core
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ChannelPermissionType } from './channel-permission-type';

/**
 * 
 * @export
 * @interface AddUserToChannelRequest
 */
export interface AddUserToChannelRequest {
    /**
     * 
     * @type {string}
     * @memberof AddUserToChannelRequest
     */
    'targetUserId': string;
    /**
     * 
     * @type {ChannelPermissionType}
     * @memberof AddUserToChannelRequest
     */
    'channelPermissionType': ChannelPermissionType;
}



