/* tslint:disable */
/* eslint-disable */
/**
 * BlockInfrastructure-Core
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface FileProjectionResponse
 */
export interface FileProjectionResponse {
  /**
   *
   * @type {string}
   * @memberof FileProjectionResponse
   */
  fileId: string;
  /**
   *
   * @type {string}
   * @memberof FileProjectionResponse
   */
  contentDispositionFileName: string;
  /**
   *
   * @type {string}
   * @memberof FileProjectionResponse
   */
  contentDispositionName: string;
  /**
   *
   * @type {string}
   * @memberof FileProjectionResponse
   */
  contentType: string;
  /**
   *
   * @type {number}
   * @memberof FileProjectionResponse
   */
  fileSize: number;
}
