/* tslint:disable */
/* eslint-disable */
/**
 * BlockInfrastructure-Core
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PluginInstallationProjection
 */
export interface PluginInstallationProjection {
  /**
   *
   * @type {string}
   * @memberof PluginInstallationProjection
   */
  channelId?: string | null;
  /**
   *
   * @type {string}
   * @memberof PluginInstallationProjection
   */
  installedAt?: string;
}
