/* tslint:disable */
/* eslint-disable */
/**
 * BlockInfrastructure-Core
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PluginTypeDefinition
 */
export interface PluginTypeDefinition {
  /**
   *
   * @type {string}
   * @memberof PluginTypeDefinition
   */
  fieldName?: string | null;
  /**
   *
   * @type {string}
   * @memberof PluginTypeDefinition
   */
  fieldType?: string | null;
  /**
   *
   * @type {string}
   * @memberof PluginTypeDefinition
   */
  fieldDescription?: string | null;
  /**
   *
   * @type {boolean}
   * @memberof PluginTypeDefinition
   */
  isRequired?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof PluginTypeDefinition
   */
  isSecret?: boolean;
  /**
   *
   * @type {string}
   * @memberof PluginTypeDefinition
   */
  defaultValue?: string | null;
}
