/* tslint:disable */
/* eslint-disable */
/**
 * BlockInfrastructure-Core
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const PricingMachineType = {
    VirtualMachine: 'VirtualMachine',
    WebServer: 'WebServer',
    DatabaseServer: 'DatabaseServer'
} as const;

export type PricingMachineType = typeof PricingMachineType[keyof typeof PricingMachineType];



