/* tslint:disable */
/* eslint-disable */
/**
 * BlockInfrastructure-Core
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SketchResponse
 */
export interface SketchResponse {
  /**
   * 스케치의 Unique ID입니다.
   * @type {string}
   * @memberof SketchResponse
   */
  sketchId: string;
  /**
   * 스케치의 이름입니다.
   * @type {string}
   * @memberof SketchResponse
   */
  name: string;
  /**
   * 스케치의 설명입니다.
   * @type {string}
   * @memberof SketchResponse
   */
  description: string;
  /**
   * 스케치의 채널 ID입니다.
   * @type {string}
   * @memberof SketchResponse
   */
  channelId: string;
  /**
   * 스케치의 블록 스케치입니다.
   * @type {any}
   * @memberof SketchResponse
   */
  blockSketch: any;
  /**
   * 생성일
   * @type {string}
   * @memberof SketchResponse
   */
  createdAt: string;
  /**
   * 마지막 수정일
   * @type {string}
   * @memberof SketchResponse
   */
  updatedAt: string;
  /**
   *
   * @type {string}
   * @memberof SketchResponse
   */
  thumbnailUrl?: string | null;
}
